name: 'Scribe evidence generator'
description: 'Generate Software Bill Of Materials (SBOM) for container images, filesystems and git repositories'
author: Mikey Strauss
outputs:
  OUTPUT_PATH:
    description: 'evidence output file path'
inputs:
  type:
    description: 'Target source type options=[docker,docker-archive, oci-archive, dir, registry, git]'
    default: registry
  target:
    description: 'Target object name format=[<image:tag>, <dir path>, <git url>]'
    required: true
  verbose:
    description: 'Log verbosity level [-v,--verbose=1] = info, [-vv,--verbose=2] = debug'
    default: 1
  config:
    description: 'Application config file'
  format:
    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json predicate-cyclonedx-json attest-slsa statement-slsa predicate-slsa]'
  output-directory:
    description: 'Report output directory'
    default: ./scribe/valint
  output-file:
    description: 'Output result to file'
  product-key:
    description: 'Custom/project product key'
  label:
    description: 'Custom label'
  env:
    description: 'Custom env'
  filter-regex:
    description: 'Filter out files by regex'
  filter-scope:
    description: 'Filter packages by scope'
  package-type:
    description: 'Select package type'
  package-group:
    description: 'Select package group'
  attach-regex:
    description: 'Attach files content by regex'
  force:
    description: 'Force overwrite cache'
    default: false
  attest-config:
    description: 'Attestation config map'
  attest-name:
    description: 'Attestation config name (default "valint")'
  attest-default:
    description: 'Attestation default config, options=[sigstore sigstore-github x509]'
    default: sigstore-github
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  scribe-client-id:
    description: 'Scribe client id' 
  scribe-client-secret:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url'
  scribe-login-url:
    description: 'Scribe auth login url' 
  scribe-audience:
    description: 'Scribe auth audience' 
  context-dir:
    description: 'Context dir' 
  components:
    description: 'Select sbom components groups, options=[metadata layers packages files dep]'
  final-artifact:
    description: 'Mark as final artifact'
    default: false
  oci: 
    description: 'Enable OCI store'
    default: false
  oci-repo:
    description: 'Select OCI custom attestation repo'

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/valint:dev-latest
  args:
    - bom
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
    - ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }}
    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
    - ${{ inputs.filter-regex && '--filter-regex=' }}${{ inputs.filter-regex }}
    - ${{ inputs.filter-scope && '--filter-scope=' }}${{ inputs.filter-scope }}
    - ${{ inputs.package-type && '--package-type=' }}${{ inputs.package-type }}
    - ${{ inputs.package-group && '--package-group=' }}${{ inputs.package-group }}
    - ${{ inputs.attach-regex && '--attach-regex=' }}${{ inputs.attach-regex }}
    - --context-type=github
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    - ${{ inputs.force && '--force=' }}${{ inputs.force }}
    - ${{ inputs.attest-name && '--attest.name=' }}${{ inputs.attest-name }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }}
    - ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.scribe-login-url && '--scribe.login-url=' }}${{ inputs.scribe-login-url }}
    - ${{ inputs.scribe-audience && '--scribe.auth.audience=' }}${{ inputs.scribe-audience }}
    - ${{ inputs.context-dir && '--scribe.context-dir=' }}${{ inputs.context-dir }}
    - ${{ inputs.components && '--components=' }}${{ inputs.components }}
    - ${{ inputs.final-artifact && '--final-artifact=' }}${{ inputs.final-artifact }}
    - ${{ inputs.oci && '--oci=' }}${{ inputs.oci }}
    - ${{ inputs.oci-repo && '--oci-repo=' }}${{ inputs.oci-repo }}



branding:
  icon: shield
  color: green
