name: Scribe evidence generator
description: Collect, Create and Store evidence for artifacts (SBOMs,SLSA provenance) or any third-party tools.
author: Mikey Strauss
outputs:
  OUTPUT_PATH:
    description: evidence output file path
  slsa_path:
    description: slsa evidence output file path
  sbom_path:
    description: sbom evidence output file path
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>]
    required: true
  attach-regex:
    description: Attach files content by regex
  components:
    description: Select sbom components groups, options=[metadata layers packages syft files dep commits]
    default: metadata,layers,packages,syft,files,dep,commits
  compress:
    description: Compress content (generic evidence)
  force:
    description: Force overwrite cache
  format:
    description: Evidence format, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json predicate-cyclonedx-json attest-slsa statement-slsa predicate-slsa statement-generic attest-generic]
    default: cyclonedx-json
  package-exclude-type:
    description: Exclude package type, options=[ruby python javascript java dpkg apkdb rpm go-mod rust binary sbom]
  package-group:
    description: Select package group, options=[index install all]
  package-type:
    description: Select package type, options=[ruby python javascript java dpkg apkdb rpm go-mod rust binary sbom]
    default: ruby,python,javascript,java,dpkg,apkdb,rpm,go-mod,rust,binary,sbom
  app-name:
    description: Logical application name
  app-version:
    description: Logical application version
  attest-config:
    description: Attestation config path
  attest-default:
    description: Attestation default config, options=[sigstore sigstore-github x509]
    default: sigstore
  backoff:
    description: Backoff duration
    default: 15s
  cache-enable:
    description: Enable local cache
    default: true
  config:
    description: Configuration file path
  context-dir:
    description: Context dir
  env:
    description: Environment keys to include in sbom
  filter-regex:
    description: Filter out files by regex
    default: '**/*.pyc,**/.git/**'
  filter-scope:
    description: Filter packages by scope
  git-branch:
    description: Git branch in the repository
  git-commit:
    description: Git commit hash in the repository
  git-tag:
    description: Git tag in the repository
  label:
    description: Add Custom labels
  level:
    description: Log depth level, options=[panic fatal error warning info debug trace]
  oci:
    description: Enable OCI store
  oci-repo:
    description: Select OCI custom attestation repo
  output-directory:
    description: Output directory path
    default: ./scribe/valint
  output-file:
    description: Output file name
  pipeline-name:
    description: Pipeline name
  predicate-type:
    description: Custom Predicate type (generic evidence format)
    default: http://scribesecurity.com/evidence/generic/v0.1
  product-key:
    description: Product Key
  product-version:
    description: Product Version
  scribe-auth-audience:
    description: Scribe auth audience
    default: api.production.scribesecurity.com
  scribe-audience:
    description: Scribe auth audience
    default: api.production.scribesecurity.com
    deprecationMessage: "Please use scribe-auth-audience instead"
  scribe-client-id:
    description: Scribe Client ID
  scribe-client-secret:
    description: Scribe Client Secret
  scribe-enable:
    description: Enable scribe client
  scribe-login-url:
    description: Scribe login url
    default: https://scribesecurity-production.us.auth0.com
  scribe-url:
    description: Scribe API Url
    default: https://api.production.scribesecurity.com
  timeout:
    description: Timeout duration
    default: 120s
  verbose:
    description: Log verbosity level [-v,--verbose=1] = info, [-vv,--verbose=2] = debug
    default: 1
runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/valint:dev-latest
  args:
    - bom
    - ${{ inputs.target}}
    - ${{ inputs.attach-regex && '--attach-regex=' }}${{ inputs.attach-regex }}
    - ${{ inputs.components && '--components=' }}${{ inputs.components }}
    - ${{ inputs.compress && '--compress=' }}${{ inputs.compress }}
    - ${{ inputs.force && '--force=' }}${{ inputs.force }}
    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
    - ${{ inputs.package-exclude-type && '--package-exclude-type=' }}${{ inputs.package-exclude-type }}
    - ${{ inputs.package-group && '--package-group=' }}${{ inputs.package-group }}
    - ${{ inputs.package-type && '--package-type=' }}${{ inputs.package-type }}
    - ${{ inputs.app-name && '--app-name=' }}${{ inputs.app-name }}
    - ${{ inputs.app-version && '--app-version=' }}${{ inputs.app-version }}
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.backoff && '--backoff=' }}${{ inputs.backoff }}
    - ${{ inputs.cache-enable && '--cache-enable=' }}${{ inputs.cache-enable }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - ${{ inputs.context-dir && '--context-dir=' }}${{ inputs.context-dir }}
    - --context-type=github
    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
    - ${{ inputs.filter-regex && '--filter-regex=' }}${{ inputs.filter-regex }}
    - ${{ inputs.filter-scope && '--filter-scope=' }}${{ inputs.filter-scope }}
    - ${{ inputs.git-branch && '--git-branch=' }}${{ inputs.git-branch }}
    - ${{ inputs.git-commit && '--git-commit=' }}${{ inputs.git-commit }}
    - ${{ inputs.git-tag && '--git-tag=' }}${{ inputs.git-tag }}
    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
    - ${{ inputs.level && '--level=' }}${{ inputs.level }}
    - ${{ inputs.oci && '--oci=' }}${{ inputs.oci }}
    - ${{ inputs.oci-repo && '--oci-repo=' }}${{ inputs.oci-repo }}
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    - ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }}
    - ${{ inputs.pipeline-name && '--pipeline-name=' }}${{ inputs.pipeline-name }}
    - ${{ inputs.predicate-type && '--predicate-type=' }}${{ inputs.predicate-type }}
    - ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }}
    - ${{ inputs.product-version && '--product-version=' }}${{ inputs.product-version }}
    - ${{ inputs.scribe-auth-audience && '--scribe.auth.audience=' }}${{ inputs.scribe-auth-audience }}
    - ${{ inputs.scribe-audience && '--scribe.auth.audience=' }}${{ inputs.scribe-audience }}
    - ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }}
    - ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }}
    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-login-url && '--scribe.login-url=' }}${{ inputs.scribe-login-url }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.timeout && '--timeout=' }}${{ inputs.timeout }}
    - ${{ inputs.verbose && '--verbose=' }}${{ inputs.verbose }}
branding:
  icon: shield
  color: green
